apiVersion: v1
kind: Namespace
metadata:
  name: sriov-device-plugin
  labels:
    name: sriov-device-plugin
    openshift.io/run-level: "0"
  annotations:
    openshift.io/node-selector: "" #override default node selector
    openshift.io/description: "SRIOV Device Plugin components"
