apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sriov-device-plugin
  namespace: sriov-device-plugin
  annotations:
    kubernetes.io/description: |
      This daemon set launches the SR-IOV Network Device Plugin.
spec:
  selector:
    matchLabels:
      app: sriovdp
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sriovdp
        component: network
        type: infra
        openshift.io/component: network
    spec:
      hostNetwork: true
      # The plugin will currently fail on nodes that do not have SRIOV capable
      # hardware; could be fixed with automatic node labels or something
      nodeSelector:
        beta.kubernetes.io/os: linux
      tolerations:
      - operator: Exists
      containers:
      - name: sriovdp
        image: {{.SRIOVDevicePluginImage}}
        args:
        - --log-level=10
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: false
        volumeMounts:
        - name: devicesock
          mountPath: /var/lib/kubelet/device-plugins/
          readOnly: false
        - name: net
          mountPath: /sys/class/net
          readOnly: true
      volumes:
        - name: devicesock
          hostPath:
            path: /var/lib/kubelet/device-plugins/
        - name: net
          hostPath:
            path: /sys/class/net

