kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: ovs-node
  namespace: openshift-ovn-kubernetes
  annotations:
    kubernetes.io/description: |
      This daemonset launches  Open vSwitch per-node networking components.
    release.openshift.io/version: "{{.ReleaseVersion}}"
spec:
  selector:
    matchLabels:
      app: ovs-node
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ovs-node
        component: network
        type: infra
        openshift.io/component: network
        kubernetes.io/os: "linux"
    spec:
      serviceAccountName: ovn-kubernetes-node
      hostNetwork: true
      hostPID: true
      priorityClassName: "system-node-critical"
      # volumes in all containers:
      # (container) -> (host)
      # /etc/openvswitch -> /var/lib/openvswitch/etc - ovsdb system id
      # /var/lib/openvswitch -> /var/lib/openvswitch/data - ovsdb data
      # /run/openvswitch -> tmpfs - ovsdb sockets
      # /env -> configmap env-overrides - debug overrides
      containers:
      # ovsdb and ovs-vswitchd
      - name: ovs-daemons
        image: "{{.OvnImage}}"
        command:
        - /bin/bash
        - -c
        - |
          #!/bin/bash
          set -euo pipefail
          set -x
          gdbus call --system \
            --dest org.freedesktop.systemd1 \
            --object-path /org/freedesktop/systemd1 \
            --method org.freedesktop.systemd1.Manager.StartUnit openvswitch.service replace
          WAIT=10
          while ( [[ ! -f /run/openvswitch/ovsdb-server.pid ]] || [[ ! -f /run/openvswitch/ovs-vswitchd.pid ]] ) && [[ ${WAIT} -gt 0 ]]; do
              sleep 1
              (( WAIT-- ))
              ls -alZ /run/openvswitch || 0
              ls -alZ /var/log/openvswitch || 0
          done
          [[ ${WAIT} -gt 0 ]] || exit 1
          tail -F --pid=$(cat /run/openvswitch/ovs-vswitchd.pid) /var/log/openvswitch/ovs-vswitchd.log &
          tail -F --pid=$(cat /run/openvswitch/ovsdb-server.pid) /var/log/openvswitch/ovsdb-server.log &
          wait
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /run
          name: host-run
        - mountPath: /var/log
          name: host-var-log
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        terminationMessagePolicy: FallbackToLogsOnError
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - |
              set -x
              gdbus call --system \
                --dest org.freedesktop.systemd1 \
                --object-path /org/freedesktop/systemd1/unit/openvswitch_2eservice \
                --method org.freedesktop.DBus.Properties.Get org.freedesktop.systemd1.Unit ActiveState | grep active
          initialDelaySeconds: 15
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - |
              set -x
              gdbus call --system \
                --dest org.freedesktop.systemd1 \
                --object-path /org/freedesktop/systemd1/unit/openvswitch_2eservice \
                --method org.freedesktop.DBus.Properties.Get org.freedesktop.systemd1.Unit ActiveState | grep active
          initialDelaySeconds: 15
          periodSeconds: 5
        terminationGracePeriodSeconds: 10

      nodeSelector:
        beta.kubernetes.io/os: "linux"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: network.operator.openshift.io/external-openvswitch
                operator: DoesNotExist        
      volumes:
      - name: host-run
        hostPath:
          path: /run
      - name: host-var-log
        hostPath:
          path: /var/log
      tolerations:
      - operator: "Exists"
